version: "2"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=perndb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pern:
    image: pern:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - .env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  postgres_data: {}

networks:
  default:
    ipam:
      config:
        - subnet: 172.21.0.0/16
