FROM balenalib/%%BALENA_MACHINE_NAME%%-node:15-stretch-run

WORKDIR /usr/src/app
COPY package.json ./
RUN JOBS=MAX npm install --include=dev && rm -rf /tmp/*
COPY . ./
RUN JOBS=MAX npm run build
ENV UDEV=1

CMD ["npm", "run", "node-prod"]
