FROM balenalib/%%BALENA_MACHINE_NAME%%-node:15-stretch-run

WORKDIR /usr/src/app
COPY package.json ./
RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*
COPY . ./
ENV UDEV=1

CMD ["npm", "run", "start"]
