version: "3"

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pern:
    image: pern:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres_data: {}

networks:
  default:
    ipam:
      config:
        - subnet: 172.21.0.0/16
